### ISSUE TITLE
awesomewm config written in fennel lisp

### ISSUE THREAD

**Issue by erikLundstedt** [elken/awesome#1]
if you want to have a look at an awesome-wm config written in lisp, I am curently daily-driving [this one](https://gitlab.com/Erik.Lundstedt/dotconfigfiles/-/tree/master/.config/awesome) I wrote in [fennel](https://github.com/bakpakin/Fennel) based on the default one but modified quite a bit
I only tell you this because I know you use emacs and such probably like lisp

hope you enjoy using awesome-wm,

**Comment by elken** [comment]
Went through fennel, the tooling is awful and has a _long_ way to go to catch up.

**Comment by erikLundstedt** [comment]
> Went through fennel, the tooling is awful and has a _long_ way to go to catch up.

I am using it on a daily basis
my website is technically written in it
as well as most of the software I use on a daily basis(including ones that arent meant to be configured in lua)
